* Chapter 1
  Trying to do a brief overview of some of the terms and important concepts
  in the /"Invitation to Metatheory"/

  A reminder: Doing metatheory is about /relations/. We are not studying Metatheory but using it
  to talk about theories.

  | Vocabulary                 | Symbol                                                                                                        | Definition                                           |
  |----------------------------+---------------------------------------------------------------------------------------------------------------+------------------------------------------------------|
  | *Propositional Signature*  | \Sigma                                                                                                        | Collection of Elementary Sentences                   |
  | *Context*                  | \(\phi_1\dots\phi_n\) OR \Delta, \Gamma                                                                       | Finite collection of Sentences/Sequences             |
  | *Derivability*             | \vdash                                                                                                        | Smallest relation between sets of Sent               |
  |                            |                                                                                                               | Syntatically entails                                 |
  | *Proof*                    | \Delta \vdash \phi                                                                                            |                                                      |
  | *Provable*                 | \vdash \phi OR \top                                                                                           |                                                      |
  | *Not Provable*             | \bot OR \(\not \top\)                                                                                         |                                                      |
  | *Interpretation/Valuation* | f: \Sigma \rightarrow {true, false}                                                                           |                                                      |
  | *Propositional Theory*     | T ; \Sigma \wedge \Delta \in \Sigma                                                                           |                                                      |
  | *Tarski Truth*             | v(\phi) = 1 \rightarrow \phi is true in v                                                                     | v = interp. of \Sigma and \phi = sent. \in \Sigma    |
  | *Model*                    | v(\phi) = 1 \forall \phi \in \Delta                                                                           | v is a model of \Delta which is \in \Sigma sent.     |
  | *Consistent*               | \Delta has at least one model v                                                                               |                                                      |
  | *Inconsistent*             | \Delta has no models v                                                                                        |                                                      |
  | *Proof of Relative Cons.*  |                                                                                                               | X theory \rightarrow models of accepted Y            |
  |                            |                                                                                                               | Y = Boolean Algebra / Set Theory                     |
  | *Semantically entails*     | v(\phi) = 1 \forall \phi \in \Delta \rightarrow \Delta \vDash \phi                                            | \Delta = set of \Sigma sent.; \phi = \Sigma sent.    |
  |                            | \Delta semantically entails \phi                                                                              |                                                      |
  | *Soundness*                | \Delta \vdash \phi \rightarrow \Delta \vDash \phi                                                             | If proof then truth table to match                   |
  | *Completeness*             | \Delta \vDash \phi \rightarrow \Delta \vdash \phi                                                             | If truth table then must be proof                    |
  | *Compactness*              | \forall \(\Delta_F \subseteq \Delta\) cons.\rightarrow \Delta cons.                                           | \Delta set of sentences. \(\Delta_F\) finite subset. |
  | *Complete Theory*          | \(\Delta cons. \wedge \forall \phi \in \Sigma , \Delta \vDash \phi \vee \Delta \vDash \not \phi\)             | T consists of axioms \Delta \in \Sigma               |
  | *Deductive Closure*        | Cn(T)=T\implies {Sent(\Sigma)}                                                                                | T theory in \Sigma                                   |
  | *Reconstrual*              | f: \Sigma \rightarrow Sent(\Sigma\prime)                                                                      |                                                      |
  | *Substitution*             | \(\forall f:\Sigma\rightarrow \Sigma\prime , \phi \vdash \psi \rightarrow f(\phi) \vdash f(\psi)\)            | Where f is a reconstrual                             |
  | *Translation*              | T \vdash \phi \rightarrow T\prime \vdash f(\phi)                                                              | f is a special reconstrual                           |
  | *Equality of Trans.*       | \(T\prime \vdash f(p) \iff g(p) \forall p \in \Sigma \)                                                       | f \simeq g; f, g trans. from T to T\prime            |
  | *Homotopy Equiv.*          | \exist f: T\rightarrow T\prime \wedge g: T\prime\rightarrow T s.t. gf \simeq 1_T \wedge fg \simeq 1_{T\prime} |                                                      |



  Two Propositional Constants are defined by identity and are dependent
  on the signature they are a part of.

  *Bare Set* is related to the Leibniz's identity of indiscernibles which states that
  there cannot be separate objects or enitites that have all their properites in common.
  What this means, is essentially that a Bare Set for a Propositional Signature just means
  that there can be separate objects with all the same common properties. Nothing stands closer
  together in relation

  The Possible set of Sentences that can be formed from \Sigma is called
  the set Sent(\Sigma). These rules are the following:

  1) \phi \in \Sigma \rightarrow \phi \in Sent(\Sigma)
  2) \phi \in Sent(\Sigma) \rightarrow (\not \phi) \in Sent(\Sigma)
  3) \phi \in Sent(\Sigma) \wedge \psi \in Sent(\Sigma) \rightarrow (\phi \wedge \psi) \in Sent(\Sigma), (\phi \vee \psi) \in Sent(\Sigma), \wedge  (\phi \rightarrow \psi) \in Sent(\Sigma)
  4) Nothing is in Sent(\Sigma) unless it enters one of the previous clauses

  *Sentence:* Finite string of symbols and contains finitely many propositional constants.

  Unions are commutative in Contexts.
** Proof by Induction
  1) Show that some property of interest P, holds of the elements of \Sigma
  2) Show that [P holds of \phi \rightarrow P holds of \psi]
  3) Show if P holds of \phi and \psi \rightarrow P holds of \phi \wedge \psi, \phi \vee \psi, and \phi \rightarrow \psi

  We allow for empty contexts as well

** Rules for Turnstile
  1) \(\vdash\) is closed under the previously given logical clauses
  2) \Delta \vdash \phi and \Delta \subseteq \(\Delta_0\) , then \(\Delta_0\) \vdash \phi . (*Monotonicity*)

  \Delta , \phi \vdash \bot \rightarrow \Delta \vdash \(\not \phi\)

  Semantics fundamentally differs from Syntax by introducing the concept of Truth 
  and false; Essentially, introducing a world

  Interpretation v of \Sigma extends to a function v: Sent(\Sigma) \rightarrow {0,1}
  by the following clauses:
  1) v(\not \phi) = \iff v(\phi) = 0
  2) v(\phi \wedge \psi) = 1 \iff v(\phi) = 1 \wedge v(\psi) = 1.
  3) v(\phi \vee \psi) = 1 \iff v(\phi) = 1 \vee v(\psi) = 1
  4) v(\phi \rightarrow \psi) = v(\not \phi \vee \psi).

  Sent(\Sigma) could be thought of as simply sentences using the vocabulary of the \Sigma to create sentences without
  being interpreted. When we make it into a function/interpretation v where the set of sentences is mapped
  to a set {1,0}, we could say that it then endows the senteces/symbols with meaning due to our judgement on these
  sentences. However, it is important to note that the domain of predicate logic interpretation must be a *set*. End stop. This
  is something that can be demonstrated using set theory. The World is not a consequence of set theory \therefore the world is not a set.
  They are of two different qualities.

  | Abstract | Concrete |
  |----------+----------|
  | Set      | World    |

  Can write T instead of \Delta, but the formulation of \Sigma affects T.\\
  e.g. p would be different in \Sigma = {p} than in \Sigma = {p,q}

  A Concept defined for sets of sentences such as consistency can also apply
  to Theories but, /again/, it must be emphasized that a theory is always the same:
  \[T = {\Sigma , \Delta \in \Sigma}\]

  Where \Sigma is a Propositional Sig. and \Delta are a set of sentences in that signature.

** Exercise 1.3.8


  *Question* For \Delta a set of \Sigma sentences and for \Sigma sentences \phi and \psi, if \Delta, \phi \vDash \psi
  then \Delta \vDash \phi \rightarrow \psi

  Assume \Delta , \phi \vDash \psi and that \exists v \in \Sigma s.t. \forall \chi \in \Delta : 
  v(\chi) = 1 and v(\phi \rightarrow \psi) = 0

  By the material conditional we can do the following move

  This thereby leaves us with the following result:

  v(\phi) = 1 and v(\psi) = 0

  However, we assumed \Delta, \phi \vDash \psi which is impossible if
  \psi = 0. Therefore, there is a contradiction. Q.E.D \square

  *Another Solution:*
  Suppose that \Delta, \phi \vDash \psi. We want to show that any model v of \Delta is such that
  v(\phi \rightarrow \psi) = 1, i.e.,
  \[v(\not \phi) = 1 or v(\psi) = 1\]

  So, given any such interpretation v. Either (i) v(\phi) = 1 or (ii) v(\not \phi) = 1.
  If (i), then v is a model of \Delta, \phi, since it is a model of \Delta. Hence by our original assumption and
  the definition of semantic entailment v(\psi) = 1 and we are done, since (*) follows.
  If (ii), then we are also done, since (*) follows. \square

** Exercise 1.3.9 **
  Show that \Delta \vDash \phi \iff \Delta \cup {\not \phi } is inconsistent. Here
  \Delta \cup {\not \phi} is the theory consisting of \not \phi and all sentences in \Delta.

  Suppose that \Delta \vDash \phi and \Delta \cup {\not \phi} is consistent. This means
  that we can find a model v for \Delta s.t. v(\chi)=1 \forall \chi \in \Delta. This would
  mean that both v(\phi) and v(\not \phi) = 1. However, this isn't possible given the fact
  that one of the clauses of an interpretation is that v(\not \phi)=1 \iff v(\phi) = 1 contradicting
  our initial assumption.\square
** Parameters for Reconstruals 

  1) for p in \Sigma, \(\bar{f} (p) = f(p)\)
  2) \forall \phi, \(\bar{f}(\not \phi) = \not \bar{f}(\phi)\)
  3) binary circles can be taken out to function f

** Exercise 1.3.16 **
  Let T\prime = {p} \in \Sigma\prime and \Sigma\prime = {p,q}. Show that T\prime is not complete.

  Proof by Contradiction:
  Assume that T\prime is complete, this means that T\prime is consistent(\Delta has at least one model) and that
  \(\forall \phi \in \Sigma\prime;\Delta \vDash \phi \vee \Delta \vDash \not \phi\).
  However, T\prime only describes p,  so although we can say \(\Delta \vDash p\), 
  we cannot say anything about q in relation to \Delta which means we can't say that \(\Delta \vDash q\) or \Delta\vDash \not q 

** Exercise 1.3.17
  Show that Cn(Cn(T)) = Cn(T).

  Cn(T) is a deductive closure which is the set of \Sigma sentences that is implied by T.

** Exercise 1.4.7
  Prove that if v is a model of T\prime , and f:T\rightarrow T\prime is a translation, then
  \(v \circ f\) is a model of T. Here \(v \circ f\) is the interpretation of \Sigma optained by applying
  f first, and then applying v.


** Lingering Questions: 
  What does it mean for \Delta to have more than one model?
 
* Week 2 
** Sets is a Category (29)
| Terms        | Symbology                               | Definition                                                  |
| Category     |                                         | Objects and arrows                                          |
| Monomorphism | g: Z\rightarrow X                       | fg=fh\rightarrow g=h                                        |
|              | h: Z\rightarrow X                       | where f: X\rightarrow Y                                     |
| Epimorphism  | g: Y\rightarrow Z                       | gf=hf, then g=h                                             |
|              | h: Y\rightarrow Z                       |                                                             |
| Isomorphism  | \exists g:Y\rightarrow X                | gf=\(1_X\) and fg=\(1_Y\)                                   |
|              |                                         | X\simeq Y                                                   |
| *THEORIES*   |                                         |                                                             |
| Conservative | T'\vdash f(\phi)\rightarrow T\vdash\phi | \forall \phi \in Sent(\Sigma)                               |
|              |                                         |                                                             |
| Ess. surj.   | T'\vdash \phi \iff f(\psi)              | \(\forall \phi \in \Sigma^\prime; \exists \psi \in \Sigma\) |
|              |                                         |                                                             |

We are going to be looking at the general theory of categories. 
To do this we are going to look at Set Theory as an example. In this case,
the theory of sets has objects called sets and relations called functions.

What does it mean to say a set is category? It means the following

1) Every function f has a domain set \(d_0f\) and a codomain set \(d_1f\).
   1) \(f:X\rightarrow Y\)indicates that \(d_0f=X\) \(d_1f=Y\)
2) Compatible functions can be composed.
   1) e.g. can have transitivity f: x\rightarrow y g: y\rightarrow z \(f \circ g: x\rightarrow z\)
   2) These compositions can also be associative
   3) \(h \circ (g \circ f) = (h \circ g) \circ f)\)
3) \forall X | X is a set, there is a function \(1_X:X\rightarrow X\) that acts as a left and right identity relative to composition.

In short, there are objects, arrows, composition with transitivity and associativity, and identity which should 
conform to equation.

*Containment or \in is /not/ a primitive notion of the Elemental Theory of the Category of Sets*

** Chapter 3.1 On the Category of Propositional Theories
*Th* is the category of propositional Theories

f:T\rightarrow T'\\
g:T\rightarrow T'\\
f and g are equal, f\simeq g, just in case T' \vdash f(\phi) \iff g(\phi) \forall \phi \in 
Sent(\Sigma)

** Proving that conservative translations are monomorphic
Suppose first that f is conservative with two granslations g, h from T'' \rightarro T s.t.
\(f\circ g = f\circ h\).
